export const SITE_CONFIG = {
  name: "Ashton's Auto Detailing",
  tagline: "Mobile Car Detailing in Duncan, BC",
  description:
    "Professional mobile interior and exterior detailing delivered directly to your home or workplace. Serving Duncan, Cowichan Valley, and surrounding areas in BC.",
  phone: "250-709-1371",
  phoneHref: "tel:2507091371",
  email: "ashtonsly1@gmail.com",
  emailHref: "mailto:ashtonsly1@gmail.com",
  instagramUrl: "https://www.instagram.com/ashtons.autodetail/",
  domain: "https://ashtonsautodetail.ca",
  location: {
    city: "Duncan",
    region: "BC",
    country: "Canada",
    regionFull: "Cowichan Valley, British Columbia",
    lat: "48.7784",
    lng: "-123.7079",
  },
  serviceAreas: [
    "Duncan",
    "Cowichan Bay",
    "Maple Bay",
    "Cobble Hill",
    "Mill Bay",
    "Shawnigan Lake",
    "Chemainus",
    "Crofton",
    "Ladysmith",
    "Lake Cowichan",
  ],
  keywords: [
    "mobile car detailing Duncan BC",
    "car detailing Duncan BC",
    "auto detailing Duncan BC",
    "mobile detailing Cowichan Valley",
    "car detailing Cowichan Valley",
    "interior car detailing Duncan",
    "exterior car detailing Duncan",
    "mobile auto detailing near me",
    "car detailing near me",
    "mobile detailing near me",
    "auto detailing near me Duncan",
    "mobile car wash Duncan BC",
    "car wash near me",
    "car wash and detailing near me",
  ],
};
