export const SITE_CONFIG = {
  name: "Ashton's Auto Detail",
  tagline: "Mobile Car Detailing in Cowichan Valley",
  description:
    "Professional mobile interior and exterior detailing delivered directly to your home or workplace. Serving Duncan, Cowichan Valley, and surrounding areas in BC.",
  phone: "250-709-1371",
  phoneHref: "tel:2507091371",
  email: "ashtonsly1@gmail.com",
  emailHref: "mailto:ashtonsly1@gmail.com",
  bookingUrl: "https://cal.com/ashtonsautodetail",
  instagramUrl: "https://instagram.com/ashtonsautodetail",
  domain: "https://ashtonsautodetailing.ca", // swap when live
  location: {
    city: "Duncan",
    region: "BC",
    country: "Canada",
    regionFull: "Cowichan Valley, British Columbia",
    lat: "48.7784",
    lng: "-123.7079",
  },
  serviceAreas: [
    "Duncan",
    "Cowichan Bay",
    "Maple Bay",
    "Cobble Hill",
    "Mill Bay",
    "Shawnigan Lake",
    "Chemainus",
    "Crofton",
    "Ladysmith",
  ],
  keywords: [
    "mobile car detailing Duncan",
    "car detailing Duncan BC",
    "auto detailing Duncan",
    "mobile detailing Cowichan Valley",
    "car detailing Cowichan Valley",
    "interior car detailing Duncan",
    "exterior car detailing Duncan",
    "mobile auto detailing near me",
    "car detailing near me",
    "mobile detailing near me",
  ],
};
